#include "hh/game/Amenities.h"
#include <algorithm>
#include <iomanip>
#include <sstream>
#include <stdexcept>

namespace hh::game {
namespace {
template<class E>int ei(E v){return static_cast<int>(v);}
bool validType(int v){return v>=ei(AmenityType::Gym)&&v<=ei(AmenityType::Pool);}
bool validStage(int v){return v>=ei(AmenityStage::Reserved)&&v<=ei(AmenityStage::Cancelled);}
bool overlaps(std::int64_t a0,std::int64_t a1,std::int64_t b0,std::int64_t b1){return a0<b1&&b0<a1;}
}
struct AmenitiesSystem::Impl{
 struct Amenity{AmenityConfig config;};
 struct Reservation:AmenityReservationView{bool revenuePosted{};};
 ServiceId nextId{1};std::int64_t elapsedSeconds{},revenueCents{};std::vector<Amenity> amenities;std::vector<Reservation> reservations;std::vector<AmenityServiceOutcome> outcomes;
 Amenity* findAmenity(AmenityId id){for(auto&x:amenities)if(x.config.id==id)return &x;return nullptr;}const Amenity* findAmenity(AmenityId id)const{for(auto&x:amenities)if(x.config.id==id)return &x;return nullptr;}
 bool openAt(const Amenity&a,std::int64_t second)const{if(!a.config.enabled)return false;int m=static_cast<int>((second/60)%1440);int open=a.config.openMinuteOfDay,close=a.config.closeMinuteOfDay;if(open==close)return true;if(close==1440)return m>=open;if(open<close)return m>=open&&m<close;return m>=open||m<close;}
 int activeAt(AmenityId id,std::int64_t second)const{int n=0;for(auto&r:reservations)if(r.amenityId==id&&r.stage!=AmenityStage::Cancelled&&overlaps(second,second+1,r.startSecond,r.endSecond))++n;return n;}
};
AmenitiesSystem::AmenitiesSystem():impl_(std::make_unique<Impl>()){}AmenitiesSystem::~AmenitiesSystem()=default;AmenitiesSystem::AmenitiesSystem(AmenitiesSystem&&)noexcept=default;AmenitiesSystem&AmenitiesSystem::operator=(AmenitiesSystem&&)noexcept=default;AmenitiesSystem::AmenitiesSystem(const AmenitiesSystem&o):impl_(std::make_unique<Impl>(*o.impl_)){}AmenitiesSystem&AmenitiesSystem::operator=(const AmenitiesSystem&o){if(this!=&o)impl_=std::make_unique<Impl>(*o.impl_);return *this;}
void AmenitiesSystem::addAmenity(const AmenityConfig&a){if(a.id==0||a.openMinuteOfDay<0||a.openMinuteOfDay>=1440||a.closeMinuteOfDay<0||a.closeMinuteOfDay>1440||a.capacity<=0||a.staffCapacity<0||a.cleanliness<0||a.cleanliness>10000||a.condition<0||a.condition>10000||a.priceCents<0||a.defaultDurationSeconds<=0)throw std::invalid_argument("invalid amenity");if(impl_->findAmenity(a.id))throw std::invalid_argument("duplicate amenity");impl_->amenities.push_back({a});std::sort(impl_->amenities.begin(),impl_->amenities.end(),[](auto&a,auto&b){return a.config.id<b.config.id;});}
void AmenitiesSystem::setElapsedSeconds(std::int64_t s){if(s<0)throw std::invalid_argument("invalid amenity clock");impl_->elapsedSeconds=s;}
void AmenitiesSystem::setCleanliness(AmenityId id,int v){if(v<0||v>10000)throw std::invalid_argument("invalid amenity cleanliness");auto*a=impl_->findAmenity(id);if(!a)throw std::invalid_argument("unknown amenity");a->config.cleanliness=v;}
void AmenitiesSystem::setCondition(AmenityId id,int v){if(v<0||v>10000)throw std::invalid_argument("invalid amenity condition");auto*a=impl_->findAmenity(id);if(!a)throw std::invalid_argument("unknown amenity");a->config.condition=v;}
AmenityReservationResult AmenitiesSystem::reserveAmenity(GuestId guest,const AmenityRequest&r){AmenityReservationResult result;auto*a=impl_->findAmenity(r.amenityId);if(!a){result.blockReason=AmenityBlockReason::NotFound;return result;}int duration=r.durationSeconds>0?r.durationSeconds:a->config.defaultDurationSeconds;if(guest==0||r.startSecond<impl_->elapsedSeconds||duration<=0){result.blockReason=AmenityBlockReason::InvalidRequest;return result;}std::int64_t end=r.startSecond+static_cast<std::int64_t>(duration);if(end<=r.startSecond){result.blockReason=AmenityBlockReason::InvalidRequest;return result;}if(!a->config.enabled||!impl_->openAt(*a,r.startSecond)||!impl_->openAt(*a,end-1)){result.blockReason=AmenityBlockReason::Closed;return result;}if(a->config.cleanliness<3000){result.blockReason=AmenityBlockReason::Dirty;return result;}if(a->config.condition<3000){result.blockReason=AmenityBlockReason::OutOfCondition;return result;}int sameAmenity=0,staffClaims=0;for(auto&x:impl_->reservations){if(x.stage==AmenityStage::Cancelled||!overlaps(r.startSecond,end,x.startSecond,x.endSecond))continue;if(x.guestId==guest){result.blockReason=AmenityBlockReason::GuestConflict;return result;}if(x.amenityId==r.amenityId){++sameAmenity;if(a->config.type==AmenityType::Spa)++staffClaims;}}if(sameAmenity>=a->config.capacity){result.blockReason=AmenityBlockReason::CapacityFull;return result;}if(a->config.type==AmenityType::Spa&&(a->config.staffCapacity<=0||staffClaims>=a->config.staffCapacity)){result.blockReason=AmenityBlockReason::StaffUnavailable;return result;}Impl::Reservation x;x.id=impl_->nextId++;x.guestId=guest;x.amenityId=r.amenityId;x.startSecond=r.startSecond;x.endSecond=end;x.stage=AmenityStage::Reserved;result.ok=true;result.reservationId=x.id;impl_->reservations.push_back(x);return result;}
std::vector<AmenityId> AmenitiesSystem::opportunities(GuestId guest)const{std::vector<AmenityId> result;for(auto&a:impl_->amenities){if(!impl_->openAt(a,impl_->elapsedSeconds)||a.config.cleanliness<3000||a.config.condition<3000||impl_->activeAt(a.config.id,impl_->elapsedSeconds)>=a.config.capacity)continue;bool conflict=false;for(auto&r:impl_->reservations)if(r.guestId==guest&&r.stage!=AmenityStage::Cancelled&&overlaps(impl_->elapsedSeconds,impl_->elapsedSeconds+1,r.startSecond,r.endSecond)){conflict=true;break;}if(!conflict)result.push_back(a.config.id);}return result;}
void AmenitiesSystem::tickSecond(){++impl_->elapsedSeconds;for(auto&r:impl_->reservations){if(r.stage==AmenityStage::Completed||r.stage==AmenityStage::Cancelled)continue;if(impl_->elapsedSeconds>=r.endSecond){r.stage=AmenityStage::Completed;if(!r.revenuePosted){auto*a=impl_->findAmenity(r.amenityId);if(a){int avg=(a->config.cleanliness+a->config.condition)/2;int satisfaction=std::clamp((avg-5000)/1000,-5,5);impl_->revenueCents+=a->config.priceCents;impl_->outcomes.push_back({r.id,r.guestId,r.amenityId,satisfaction,a->config.priceCents});a->config.cleanliness=std::max(0,a->config.cleanliness-250);a->config.condition=std::max(0,a->config.condition-50);}r.revenuePosted=true;}}else if(impl_->elapsedSeconds>=r.startSecond)r.stage=AmenityStage::InService;}}
void AmenitiesSystem::tickSeconds(std::int64_t s){if(s<0||s>1000000000LL)throw std::invalid_argument("invalid amenity tick duration");for(std::int64_t i=0;i<s;++i)tickSecond();}
AmenitiesSnapshot AmenitiesSystem::snapshot()const{AmenitiesSnapshot s;s.elapsedSeconds=impl_->elapsedSeconds;s.revenueCents=impl_->revenueCents;s.outcomes=impl_->outcomes;for(auto&a:impl_->amenities){AmenityView v;v.id=a.config.id;v.type=a.config.type;v.capacity=a.config.capacity;v.active=impl_->activeAt(a.config.id,impl_->elapsedSeconds);v.cleanliness=a.config.cleanliness;v.condition=a.config.condition;v.open=impl_->openAt(a,impl_->elapsedSeconds);v.cleaningRequired=v.cleanliness<6000;v.maintenanceRequired=v.condition<5000;v.priceCents=a.config.priceCents;s.amenities.push_back(v);}for(auto&r:impl_->reservations)s.reservations.push_back(r);return s;}
std::string AmenitiesSystem::save()const{std::ostringstream o;o<<"HHAMN 1\n"<<impl_->nextId<<' '<<impl_->elapsedSeconds<<' '<<impl_->revenueCents<<'\n'<<impl_->amenities.size()<<'\n';for(auto&a:impl_->amenities){auto&c=a.config;o<<c.id<<' '<<ei(c.type)<<' '<<c.openMinuteOfDay<<' '<<c.closeMinuteOfDay<<' '<<c.capacity<<' '<<c.staffCapacity<<' '<<c.cleanliness<<' '<<c.condition<<' '<<c.priceCents<<' '<<c.defaultDurationSeconds<<' '<<c.enabled<<'\n';}o<<impl_->reservations.size()<<'\n';for(auto&r:impl_->reservations)o<<r.id<<' '<<r.guestId<<' '<<r.amenityId<<' '<<r.startSecond<<' '<<r.endSecond<<' '<<ei(r.stage)<<' '<<r.revenuePosted<<'\n';o<<impl_->outcomes.size()<<'\n';for(auto&x:impl_->outcomes)o<<x.reservationId<<' '<<x.guestId<<' '<<x.amenityId<<' '<<x.satisfactionDelta<<' '<<x.revenueCents<<'\n';return o.str();}
AmenitiesSystem AmenitiesSystem::load(std::string_view data){if(data.size()>16*1024*1024)throw std::invalid_argument("amenity save too large");std::istringstream i{std::string(data)};std::string magic;int version{};i>>magic>>version;if(!i||magic!="HHAMN"||version!=1)throw std::invalid_argument("unsupported amenity save");AmenitiesSystem r;auto&d=*r.impl_;i>>d.nextId>>d.elapsedSeconds>>d.revenueCents;if(!i||d.nextId==0||d.elapsedSeconds<0||d.revenueCents<0)throw std::invalid_argument("invalid amenity state");std::size_t n{};i>>n;if(!i||n>100000)throw std::invalid_argument("invalid amenity count");for(size_t j=0;j<n;++j){AmenityConfig c;int t{};i>>c.id>>t>>c.openMinuteOfDay>>c.closeMinuteOfDay>>c.capacity>>c.staffCapacity>>c.cleanliness>>c.condition>>c.priceCents>>c.defaultDurationSeconds>>c.enabled;if(!i||!validType(t))throw std::invalid_argument("invalid saved amenity");c.type=static_cast<AmenityType>(t);r.addAmenity(c);}i>>n;if(!i||n>100000)throw std::invalid_argument("invalid amenity reservation count");d.reservations.resize(n);std::int64_t posted{};for(auto&x:d.reservations){int st{};i>>x.id>>x.guestId>>x.amenityId>>x.startSecond>>x.endSecond>>st>>x.revenuePosted;if(!i||x.id==0||x.guestId==0||!d.findAmenity(x.amenityId)||x.startSecond<0||x.endSecond<=x.startSecond||!validStage(st))throw std::invalid_argument("invalid saved amenity reservation");x.stage=static_cast<AmenityStage>(st);if(x.revenuePosted)posted+=d.findAmenity(x.amenityId)->config.priceCents;}i>>n;if(!i||n>100000)throw std::invalid_argument("invalid amenity outcome count");d.outcomes.resize(n);std::int64_t outcomeRevenue{};for(auto&x:d.outcomes){i>>x.reservationId>>x.guestId>>x.amenityId>>x.satisfactionDelta>>x.revenueCents;if(!i||x.reservationId==0||x.guestId==0||!d.findAmenity(x.amenityId)||x.revenueCents<0)throw std::invalid_argument("invalid saved amenity outcome");outcomeRevenue+=x.revenueCents;}if(posted!=d.revenueCents||outcomeRevenue!=d.revenueCents)throw std::invalid_argument("invalid saved amenity revenue");i>>std::ws;if(!i.eof())throw std::invalid_argument("unexpected amenity trailing data");return r;}
}
