#include "hh/game/Events.h"
#include <algorithm>
#include <iomanip>
#include <limits>
#include <sstream>
#include <stdexcept>

namespace hh::game {
namespace {
template<class E>int ei(E v){return static_cast<int>(v);}
bool validPhase(int v){return v>=ei(EventPhase::Confirmed)&&v<=ei(EventPhase::Cancelled);}
bool overlap(std::int64_t a0,std::int64_t a1,std::int64_t b0,std::int64_t b1){return a0<b1&&b0<a1;}
}
struct EventsSystem::Impl{
 struct Space{FunctionSpaceId id{};int capacity{};bool enabled{};};
 struct Booking:EventBookingView{int setupSeconds{},teardownSeconds{};bool revenuePosted{};std::vector<EventPhase> history;};
 ServiceId nextId{1};std::int64_t elapsedSeconds{},revenueCents{};int foodCapacityPerHour{},staffCapacity{};std::vector<Space> spaces;std::vector<Booking> bookings;
 Booking* find(EventBookingId id){for(auto&x:bookings)if(x.id==id)return &x;return nullptr;}const Booking* find(EventBookingId id)const{for(auto&x:bookings)if(x.id==id)return &x;return nullptr;}
 const Space* space(FunctionSpaceId id)const{for(auto&x:spaces)if(x.id==id)return &x;return nullptr;}
 void enter(Booking&b,EventPhase p){if(b.phase==p&&!b.history.empty())return;b.phase=p;if(b.history.empty()||b.history.back()!=p)b.history.push_back(p);if(p==EventPhase::Completed&&!b.revenuePosted){revenueCents+=b.contractCents;b.revenuePosted=true;}}
};
EventsSystem::EventsSystem():impl_(std::make_unique<Impl>()){}EventsSystem::~EventsSystem()=default;EventsSystem::EventsSystem(EventsSystem&&)noexcept=default;EventsSystem&EventsSystem::operator=(EventsSystem&&)noexcept=default;EventsSystem::EventsSystem(const EventsSystem&o):impl_(std::make_unique<Impl>(*o.impl_)){}EventsSystem&EventsSystem::operator=(const EventsSystem&o){if(this!=&o)impl_=std::make_unique<Impl>(*o.impl_);return *this;}
void EventsSystem::addFunctionSpace(const FunctionSpaceConfig&s){if(s.id==0||s.capacity<=0)throw std::invalid_argument("invalid function space");if(std::any_of(impl_->spaces.begin(),impl_->spaces.end(),[&](auto&x){return x.id==s.id;}))throw std::invalid_argument("duplicate function space");impl_->spaces.push_back({s.id,s.capacity,s.enabled});std::sort(impl_->spaces.begin(),impl_->spaces.end(),[](auto&a,auto&b){return a.id<b.id;});}
void EventsSystem::setFoodServiceCapacity(int n){if(n<0)throw std::invalid_argument("invalid event food capacity");impl_->foodCapacityPerHour=n;}
void EventsSystem::setStaffCapacity(int n){if(n<0)throw std::invalid_argument("invalid event staff capacity");impl_->staffCapacity=n;}
void EventsSystem::setElapsedSeconds(std::int64_t s){if(s<0)throw std::invalid_argument("invalid event clock");impl_->elapsedSeconds=s;}
EventQuote EventsSystem::quoteEvent(const EventRequest&r)const{EventQuote q;q.quotedCents=r.contractCents;if(r.startSecond<impl_->elapsedSeconds||r.durationSeconds<=0||r.attendees<=0||r.mealServings<0||r.setupSeconds<0||r.teardownSeconds<0||r.requiredStaffUnits<0||r.contractCents<0){q.blockReason=EventBlockReason::InvalidRequest;return q;}const Impl::Space*sp=nullptr;if(r.functionSpaceId!=0){sp=impl_->space(r.functionSpaceId);if(!sp||!sp->enabled){q.blockReason=EventBlockReason::MissingFunctionSpace;return q;}}else{for(auto&candidate:impl_->spaces)if(candidate.enabled&&candidate.capacity>=r.attendees){sp=&candidate;break;}if(!sp){q.blockReason=EventBlockReason::MissingFunctionSpace;return q;}}q.functionSpaceId=sp->id;if(sp->capacity<r.attendees){q.blockReason=EventBlockReason::InsufficientRoomCapacity;return q;}std::int64_t hours=std::max<std::int64_t>(1,(static_cast<std::int64_t>(r.durationSeconds)+3599)/3600);std::int64_t servingCapacity=hours*impl_->foodCapacityPerHour;if(r.mealServings>servingCapacity){q.blockReason=EventBlockReason::ServiceCapacity;return q;}if(r.requiredStaffUnits>impl_->staffCapacity){q.blockReason=EventBlockReason::StaffingCapacity;return q;}const auto begin=r.startSecond-r.setupSeconds;const auto end=r.startSecond+static_cast<std::int64_t>(r.durationSeconds)+r.teardownSeconds;if(begin<0||end<=begin){q.blockReason=EventBlockReason::InvalidRequest;return q;}for(auto&b:impl_->bookings)if(b.functionSpaceId==sp->id&&b.phase!=EventPhase::Cancelled&&overlap(begin,end,b.startSecond-b.setupSeconds,b.endSecond+b.teardownSeconds)){q.blockReason=EventBlockReason::TimeConflict;return q;}q.confirmable=true;q.blockReason=EventBlockReason::None;return q;}
EventBookingId EventsSystem::confirmEvent(const EventRequest&r){auto q=quoteEvent(r);if(!q.confirmable)return 0;Impl::Booking b;b.id=impl_->nextId++;b.functionSpaceId=q.functionSpaceId;b.startSecond=r.startSecond;b.endSecond=r.startSecond+r.durationSeconds;b.attendees=r.attendees;b.mealServings=r.mealServings;b.requiredStaffUnits=r.requiredStaffUnits;b.contractCents=q.quotedCents;b.setupSeconds=r.setupSeconds;b.teardownSeconds=r.teardownSeconds;b.phase=EventPhase::Confirmed;b.history.push_back(EventPhase::Confirmed);auto id=b.id;impl_->bookings.push_back(std::move(b));return id;}
EventPhase EventsSystem::phase(EventBookingId id)const{if(auto*b=impl_->find(id))return b->phase;return EventPhase::Cancelled;}
std::vector<EventPhase> EventsSystem::phaseHistory(EventBookingId id)const{if(auto*b=impl_->find(id))return b->history;return {};}
void EventsSystem::tickSecond(){++impl_->elapsedSeconds;for(auto&b:impl_->bookings){if(b.phase==EventPhase::Completed||b.phase==EventPhase::Cancelled)continue;const auto setupAt=b.startSecond-b.setupSeconds;const auto teardownEnd=b.endSecond+b.teardownSeconds;if(impl_->elapsedSeconds>=teardownEnd)impl_->enter(b,EventPhase::Completed);else if(impl_->elapsedSeconds>=b.endSecond)impl_->enter(b,EventPhase::Teardown);else if(impl_->elapsedSeconds>=b.startSecond)impl_->enter(b,EventPhase::Service);else if(impl_->elapsedSeconds>=setupAt)impl_->enter(b,EventPhase::Setup);}}
void EventsSystem::tickSeconds(std::int64_t s){if(s<0||s>1000000000LL)throw std::invalid_argument("invalid event tick duration");for(std::int64_t i=0;i<s;++i)tickSecond();}
EventsSnapshot EventsSystem::snapshot()const{EventsSnapshot s;s.elapsedSeconds=impl_->elapsedSeconds;s.revenueCents=impl_->revenueCents;for(auto&b:impl_->bookings){s.bookings.push_back(b);if(b.phase==EventPhase::Setup||b.phase==EventPhase::Service||b.phase==EventPhase::Teardown){EventWorkloadView w;w.bookingId=b.id;w.phase=b.phase;w.staffUnits=b.phase==EventPhase::Service?b.requiredStaffUnits:std::max(1,b.requiredStaffUnits/2);w.mealServings=b.phase==EventPhase::Service?b.mealServings:0;s.workloads.push_back(w);}}return s;}
std::string EventsSystem::save()const{std::ostringstream o;o<<"HHEVT 1\n"<<impl_->nextId<<' '<<impl_->elapsedSeconds<<' '<<impl_->foodCapacityPerHour<<' '<<impl_->staffCapacity<<' '<<impl_->revenueCents<<'\n'<<impl_->spaces.size()<<'\n';for(auto&s:impl_->spaces)o<<s.id<<' '<<s.capacity<<' '<<s.enabled<<'\n';o<<impl_->bookings.size()<<'\n';for(auto&b:impl_->bookings){o<<b.id<<' '<<b.functionSpaceId<<' '<<b.startSecond<<' '<<b.endSecond<<' '<<b.attendees<<' '<<b.mealServings<<' '<<b.requiredStaffUnits<<' '<<b.contractCents<<' '<<ei(b.phase)<<' '<<b.setupSeconds<<' '<<b.teardownSeconds<<' '<<b.revenuePosted<<' '<<b.history.size();for(auto p:b.history)o<<' '<<ei(p);o<<'\n';}return o.str();}
EventsSystem EventsSystem::load(std::string_view data){if(data.size()>16*1024*1024)throw std::invalid_argument("event save too large");std::istringstream i{std::string(data)};std::string magic;int version{};i>>magic>>version;if(!i||magic!="HHEVT"||version!=1)throw std::invalid_argument("unsupported event save");EventsSystem r;auto&d=*r.impl_;i>>d.nextId>>d.elapsedSeconds>>d.foodCapacityPerHour>>d.staffCapacity>>d.revenueCents;if(!i||d.nextId==0||d.elapsedSeconds<0||d.foodCapacityPerHour<0||d.staffCapacity<0||d.revenueCents<0)throw std::invalid_argument("invalid event state");std::size_t n{};i>>n;if(!i||n>100000)throw std::invalid_argument("invalid function-space count");for(size_t j=0;j<n;++j){Impl::Space s;i>>s.id>>s.capacity>>s.enabled;if(!i||s.id==0||s.capacity<=0)throw std::invalid_argument("invalid saved function space");d.spaces.push_back(s);}std::sort(d.spaces.begin(),d.spaces.end(),[](auto&a,auto&b){return a.id<b.id;});i>>n;if(!i||n>100000)throw std::invalid_argument("invalid event booking count");d.bookings.resize(n);std::int64_t posted{};for(auto&b:d.bookings){int p{};std::size_t h{};i>>b.id>>b.functionSpaceId>>b.startSecond>>b.endSecond>>b.attendees>>b.mealServings>>b.requiredStaffUnits>>b.contractCents>>p>>b.setupSeconds>>b.teardownSeconds>>b.revenuePosted>>h;if(!i||b.id==0||!validPhase(p)||b.startSecond<0||b.endSecond<=b.startSecond||b.attendees<=0||b.mealServings<0||b.requiredStaffUnits<0||b.contractCents<0||b.setupSeconds<0||b.teardownSeconds<0||h>100000)throw std::invalid_argument("invalid saved event booking");b.phase=static_cast<EventPhase>(p);b.history.resize(h);for(auto&x:b.history){int v{};i>>v;if(!i||!validPhase(v))throw std::invalid_argument("invalid saved event history");x=static_cast<EventPhase>(v);}if(b.revenuePosted)posted+=b.contractCents;}if(posted!=d.revenueCents)throw std::invalid_argument("invalid saved event revenue");i>>std::ws;if(!i.eof())throw std::invalid_argument("unexpected event trailing data");return r;}
}
