if(NOT DEFINED HH_COOKED_ASSET_ROOT OR HH_COOKED_ASSET_ROOT STREQUAL "")
    message(FATAL_ERROR "HH_COOKED_ASSET_ROOT is required")
endif()
if(NOT DEFINED HH_RUNTIME_ASSET_ROOT OR HH_RUNTIME_ASSET_ROOT STREQUAL "")
    message(FATAL_ERROR "HH_RUNTIME_ASSET_ROOT is required")
endif()
set(manifest_path "${CMAKE_CURRENT_LIST_DIR}/../GameData/AssetDefinitions/hotel_haven_asset_manifest_v2.json")
if(NOT EXISTS "${manifest_path}")
    set(manifest_path "${CMAKE_CURRENT_LIST_DIR}/../GameData/AssetDefinitions/hotel_haven_asset_manifest_v1.json")
endif()
file(READ "${manifest_path}" active_manifest)
string(JSON expected_count ERROR_VARIABLE manifest_error GET "${active_manifest}" asset_count)
if(manifest_error OR NOT expected_count MATCHES "^[0-9]+$" OR expected_count LESS 1)
    message(FATAL_ERROR "Invalid gameplay asset_count in ${manifest_path}: ${manifest_error}")
endif()

file(GLOB cooked_assets "${HH_COOKED_ASSET_ROOT}/*.hasset")
list(SORT cooked_assets COMPARE NATURAL)
list(LENGTH cooked_assets cooked_count)
if(NOT cooked_count EQUAL expected_count)
    message(FATAL_ERROR
        "Expected exactly ${expected_count} cooked .hasset files in ${HH_COOKED_ASSET_ROOT}; found ${cooked_count}")
endif()
set(expected_id 1)
foreach(asset IN LISTS cooked_assets)
    get_filename_component(name "${asset}" NAME)
    set(padded_id "${expected_id}")
    string(LENGTH "${padded_id}" digit_count)
    while(digit_count LESS 3)
        set(padded_id "0${padded_id}")
        math(EXPR digit_count "${digit_count} + 1")
    endwhile()
    set(expected_name "HH_A${padded_id}.hasset")
    if(NOT name STREQUAL expected_name)
        message(FATAL_ERROR "Cooked asset ID mismatch: expected ${expected_name}, found ${name}")
    endif()
    math(EXPR expected_id "${expected_id} + 1")
endforeach()

file(REMOVE_RECURSE "${HH_RUNTIME_ASSET_ROOT}")
file(MAKE_DIRECTORY "${HH_RUNTIME_ASSET_ROOT}")
foreach(asset IN LISTS cooked_assets)
    file(COPY "${asset}" DESTINATION "${HH_RUNTIME_ASSET_ROOT}")
endforeach()

file(GLOB staged_assets "${HH_RUNTIME_ASSET_ROOT}/*.hasset")
list(LENGTH staged_assets staged_count)
if(NOT staged_count EQUAL expected_count)
    message(FATAL_ERROR
        "Runtime asset staging produced ${staged_count} files instead of ${expected_count}")
endif()

message(STATUS
    "Staged ${staged_count} renderer-safe cooked assets to ${HH_RUNTIME_ASSET_ROOT}")
